### ISSUE TITLE
Setup Routes

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/bridge-web#10]
**Context**
We must scope the routes in **Bride-web** by the `:network` attribute. We also need organize them using the .

**User flow**
- Go on bridge url
- Click on the DropDown at the top right to select the `network`
- Select one

**Technical details**
- [x] Nested routes by `:network` id
- [x] Add route for `NotFound`
- [x] Add route for `Error`
