### ISSUE TITLE
Imporve birdge popup

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/bridge-web#112]
**Context**
We need to improve the FE for the popup so it becomes more robust and scalable. 

- [x] Change SEP to ETH

- [x] Change the fetching conditional 

- [x] ADD I18n to various pages 

- [x] Style Popup screen

- [x] Style Popup windows 

- [ ]  Add the account balance & the wallet provider to the Store, add is metamask connected to the store -> DONE

- [ ]  Clean up sone code
