### ISSUE TITLE
Refactor "Connect wallets" popUp

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/bridge-web#173]
[**Context**]
We need to refactor this popUp:
![image](https://github.com/massalabs/bridge-web/assets/72019005/d8f3dd03-275e-48dd-b002-2194d7daff28)

Follow these rules:
```coffeescript
BOTH connected -> nothing (remove rigth banner and just center both on the left)

Metamask not installed OR off -> Banner add Sepolia (https://www.figma.com/file/Evyy6hA4jxm4vUi3IyydRc/Bridge?type=design&node-id=2507-8746&mode=design&t=DiUTBBxBv0vSn1nq-0)
Massa on -> nothing

BOTH not installed OR off -> the current one implemented (https://www.figma.com/file/Evyy6hA4jxm4vUi3IyydRc/Bridge?type=design&node-id=1837-15349&mode=design&t=DiUTBBxBv0vSn1nq-0) 
  
Metamask on -> nothing
Massa not installed OR off -> Banner donwload massa station (https://www.figma.com/file/Evyy6hA4jxm4vUi3IyydRc/Bridge?type=design&node-id=2506-15367&mode=design&t=DiUTBBxBv0vSn1nq-0)
``` 

**Technical details**
- [x] #177
- [x] Metamask not installed or off
- [x] Both not installed or off
- [x] Massa not installed or off
