### ISSUE TITLE
Setup Bridge layout

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/bridge-web#9]
**Context**

Set up a layout with the correct background. This component will be rendered once and contain our application. 

After integrate the `Header` to follow the design (https://www.figma.com/file/Evyy6hA4jxm4vUi3IyydRc/Bridge?type=design&node-id=1783-10729&mode=design&t=kaqVtk0U6qrukV62-0)

![image](https://github.com/massalabs/bridge-web/assets/72019005/dd0b2dd1-8b66-4b38-bbd9-065a1a2f4c33)

**User flow**
- Go on bridge website
- See `Header` in the `Homepage`

**External dependancies:**
- [x] https://github.com/massalabs/ui-kit/issues/283
- [x] #15
- [x] #18
- [x] #21
- [x] #24
- [x] add theme select functions to layout (not a prio)
- [x] add outlet & toast to layout (not a prio)

**Technical details**

- Create Layout component 
- Add colors to layout component
- Add `Header` to layout
- Add layout to application
